{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-vp9",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-decode-vp9-1.5.1.aar",
          "url": "media3-decode-vp9-1.5.1.aar",
          "size": 1007561,
          "sha512": "031550c04441c3c1128eca4e62bbb3bd92d23a3c0d758bf579e23e958af0b950f813f83aec917da4a638e585bcdc413241772f0c55719c66d227460438aeb46c",
          "sha256": "7d8c0f06108870a70dbf5420c67c0d03489485c55abba8ce8f5b284a355beacb",
          "sha1": "1f96ab7d5cbff2a8ab841ce854d0b3c017e5ac3c",
          "md5": "52d22e538b5cda08e11b4c74c0e0f47a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-vp9-1.5.1.aar",
          "url": "media3-decode-vp9-1.5.1.aar",
          "size": 1007561,
          "sha512": "031550c04441c3c1128eca4e62bbb3bd92d23a3c0d758bf579e23e958af0b950f813f83aec917da4a638e585bcdc413241772f0c55719c66d227460438aeb46c",
          "sha256": "7d8c0f06108870a70dbf5420c67c0d03489485c55abba8ce8f5b284a355beacb",
          "sha1": "1f96ab7d5cbff2a8ab841ce854d0b3c017e5ac3c",
          "md5": "52d22e538b5cda08e11b4c74c0e0f47a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-vp9-1.5.1-sources.jar",
          "url": "media3-decode-vp9-1.5.1-sources.jar",
          "size": 8806,
          "sha512": "82e3da40998905603def4e85b3af47d12e12478e15d9e41f29c2526b5d6cf342a62f4c5363c271c74a23f4285182c00ab247f66266b2c4dbc3901ea17542b344",
          "sha256": "07d63e3a966d5ec1627ac25b81e6fad39fe6eaab5ab63b6e0d838ce504365c55",
          "sha1": "fce8af9544978db185c9941a8df3cde8c825bff2",
          "md5": "f7f4dba0240579719020bd4e4e675ebc"
        }
      ]
    }
  ]
}
